export type ThemePaletteColors = {
    background: string;
    card: string;
    secondary: string;
    foreground: string;
    mutedForeground: string;
    faint: string;
    border: string;
    borderSoft: string;
    primary: string;
    primaryForeground: string;
    accent: string;
    accentForeground: string;
    shadowTint?: string;
};

export type ThemePalette = {
    id: string;
    name: string;
    note: string;
    light: ThemePaletteColors;
    dark: ThemePaletteColors;
};

export const DEFAULT_PALETTE_ID = "paper";

export const THEME_PALETTES: [ThemePalette, ...ThemePalette[]] = [
    {
        id: "paper",
        name: "Paper",
        note: "The authored theme: cream, ink and terracotta. Selecting it removes every override rather than restating one.",
        light: {
            background: "#f7f3ec",
            card: "#fffdf8",
            secondary: "#f1ebe0",
            foreground: "#2c2926",
            mutedForeground: "#635c52",
            faint: "#7b7368",
            border: "#e6ddce",
            borderSoft: "#efe8da",
            primary: "#c8643c",
            primaryForeground: "#ffffff",
            accent: "#f4e0d6",
            accentForeground: "#a04a28",
            shadowTint: "60, 50, 38",
        },
        dark: {
            background: "#05060a",
            card: "#10131f",
            secondary: "#080d18",
            foreground: "#e6ebf5",
            mutedForeground: "#969fb0",
            faint: "#7c8499",
            border: "#1c2233",
            borderSoft: "#111726",
            primary: "#e0794c",
            primaryForeground: "#ffffff",
            accent: "rgba(224, 121, 78, 0.18)",
            accentForeground: "#f0a07e",
        },
    },
    {
        id: "slate",
        name: "Slate",
        note: "Neutral grey paper under a vivid classic blue. The safest of the ten - reach for it when the interface should disappear behind the work.",
        light: {
            background: "#f4f4f5",
            card: "#feffff",
            secondary: "#ececed",
            foreground: "#202021",
            mutedForeground: "#535455",
            faint: "#6b6c6d",
            border: "#d4d5d6",
            borderSoft: "#e4e5e6",
            primary: "#1c6be0",
            primaryForeground: "#ffffff",
            accent: "#d1e0fd",
            accentForeground: "#174ea1",
            shadowTint: "37, 39, 40",
        },
        dark: {
            background: "#0a0a0b",
            card: "#202122",
            secondary: "#131415",
            foreground: "#e9eaeb",
            mutedForeground: "#a5a7a8",
            faint: "#8a8c8d",
            border: "#37383a",
            borderSoft: "#262728",
            primary: "#8eb7f8",
            primaryForeground: "#161718",
            accent: "rgba(142, 183, 248, 0.18)",
            accentForeground: "#b8d1f8",
        },
    },
    {
        id: "graphite",
        name: "Graphite",
        note: "No hue anywhere. Black ink, white paper, and the brand is the ink - the Swiss poster reading of a UI, and the only palette that cannot age.",
        light: {
            background: "#f5f4f4",
            card: "#ffffff",
            secondary: "#edecec",
            foreground: "#212020",
            mutedForeground: "#555354",
            faint: "#6d6c6c",
            border: "#d6d4d5",
            borderSoft: "#e6e4e5",
            primary: "#232323",
            primaryForeground: "#ffffff",
            accent: "#e4e4e4",
            accentForeground: "#414141",
            shadowTint: "40, 38, 38",
        },
        dark: {
            background: "#0b0a0a",
            card: "#222021",
            secondary: "#151314",
            foreground: "#ebe9ea",
            mutedForeground: "#a8a6a7",
            faint: "#8d8b8b",
            border: "#3a3738",
            borderSoft: "#282627",
            primary: "#ededed",
            primaryForeground: "#101010",
            accent: "rgba(237, 237, 237, 0.16)",
            accentForeground: "#cccccc",
        },
    },
    {
        id: "indigo",
        name: "Indigo",
        note: "Cool-neutral paper and a saturated indigo. Reads as considered rather than corporate, and holds up on a projector.",
        light: {
            background: "#f4f4f5",
            card: "#ffffff",
            secondary: "#ececed",
            foreground: "#202021",
            mutedForeground: "#545455",
            faint: "#6c6c6d",
            border: "#d5d5d6",
            borderSoft: "#e5e5e6",
            primary: "#7e4df2",
            primaryForeground: "#ffffff",
            accent: "#e1dafc",
            accentForeground: "#5a26ba",
            shadowTint: "38, 38, 40",
        },
        dark: {
            background: "#0a0a0b",
            card: "#202022",
            secondary: "#141415",
            foreground: "#e9eaeb",
            mutedForeground: "#a6a6a8",
            faint: "#8b8b8d",
            border: "#38383a",
            borderSoft: "#272728",
            primary: "#b6a9f8",
            primaryForeground: "#171718",
            accent: "rgba(182, 169, 248, 0.18)",
            accentForeground: "#cfc9f8",
        },
    },
    {
        id: "pine",
        name: "Pine",
        note: "Warm-neutral paper with a strong forest green. Calm without going herbal - the least tiring of the ten over a long session.",
        light: {
            background: "#f4f4f4",
            card: "#fefffe",
            secondary: "#ecedec",
            foreground: "#202120",
            mutedForeground: "#535453",
            faint: "#6b6d6c",
            border: "#d4d5d4",
            borderSoft: "#e4e5e4",
            primary: "#208046",
            primaryForeground: "#ffffff",
            accent: "#c5ebd1",
            accentForeground: "#1d6236",
            shadowTint: "37, 39, 37",
        },
        dark: {
            background: "#0a0a0a",
            card: "#202120",
            secondary: "#131413",
            foreground: "#e9eae9",
            mutedForeground: "#a5a7a6",
            faint: "#8a8c8a",
            border: "#373837",
            borderSoft: "#262726",
            primary: "#3bd678",
            primaryForeground: "#161716",
            accent: "rgba(59, 214, 120, 0.18)",
            accentForeground: "#54f28e",
        },
    },
    {
        id: "olive",
        name: "Olive",
        note: "Bone paper and a sharp olive. Utilitarian in the good sense: field notebook, not dashboard.",
        light: {
            background: "#f4f4f4",
            card: "#fffffe",
            secondary: "#ececeb",
            foreground: "#202020",
            mutedForeground: "#545453",
            faint: "#6c6c6b",
            border: "#d5d5d3",
            borderSoft: "#e5e5e4",
            primary: "#63781c",
            primaryForeground: "#ffffff",
            accent: "#d8e6c3",
            accentForeground: "#4a5a19",
            shadowTint: "38, 39, 36",
        },
        dark: {
            background: "#0a0a0a",
            card: "#21211f",
            secondary: "#141413",
            foreground: "#eaeae8",
            mutedForeground: "#a7a7a5",
            faint: "#8b8c89",
            border: "#383836",
            borderSoft: "#272725",
            primary: "#a4c634",
            primaryForeground: "#171716",
            accent: "rgba(164, 198, 52, 0.18)",
            accentForeground: "#bce14c",
        },
    },
    {
        id: "ochre",
        name: "Ochre",
        note: "Barely-warm paper and a rich gold. Carries warmth without the terracotta the default already owns.",
        light: {
            background: "#f5f4f4",
            card: "#fffffe",
            secondary: "#edeceb",
            foreground: "#212020",
            mutedForeground: "#545453",
            faint: "#6d6c6b",
            border: "#d5d5d3",
            borderSoft: "#e5e5e4",
            primary: "#93681c",
            primaryForeground: "#ffffff",
            accent: "#f0ddc0",
            accentForeground: "#6b4c18",
            shadowTint: "39, 38, 36",
        },
        dark: {
            background: "#0b0a09",
            card: "#21211f",
            secondary: "#141413",
            foreground: "#eaeae8",
            mutedForeground: "#a7a7a5",
            faint: "#8c8b89",
            border: "#393836",
            borderSoft: "#272725",
            primary: "#eba733",
            primaryForeground: "#181716",
            accent: "rgba(235, 167, 51, 0.18)",
            accentForeground: "#f8c67c",
        },
    },
    {
        id: "claret",
        name: "Claret",
        note: "Off-white with a full-blooded crimson. The editorial one - masthead red, dark enough to sit under body text.",
        light: {
            background: "#f5f4f4",
            card: "#fffffe",
            secondary: "#edecec",
            foreground: "#212020",
            mutedForeground: "#555353",
            faint: "#6d6c6b",
            border: "#d6d4d4",
            borderSoft: "#e6e4e4",
            primary: "#d7282d",
            primaryForeground: "#ffffff",
            accent: "#fdd5cf",
            accentForeground: "#942021",
            shadowTint: "40, 38, 37",
        },
        dark: {
            background: "#0b0a0a",
            card: "#222020",
            secondary: "#151313",
            foreground: "#ebe9e9",
            mutedForeground: "#a8a6a5",
            faint: "#8d8b8a",
            border: "#3a3737",
            borderSoft: "#282626",
            primary: "#f9978e",
            primaryForeground: "#181716",
            accent: "rgba(249, 151, 142, 0.18)",
            accentForeground: "#f8bfb9",
        },
    },
    {
        id: "aubergine",
        name: "Aubergine",
        note: "Neutral paper and a deep magenta-purple. The most distinctive at a glance, and still quiet at arm's length.",
        light: {
            background: "#f5f4f5",
            card: "#ffffff",
            secondary: "#edeced",
            foreground: "#212021",
            mutedForeground: "#545354",
            faint: "#6d6c6d",
            border: "#d5d4d5",
            borderSoft: "#e5e4e5",
            primary: "#c328b0",
            primaryForeground: "#ffffff",
            accent: "#fecff0",
            accentForeground: "#851f77",
            shadowTint: "39, 38, 39",
        },
        dark: {
            background: "#0b0a0b",
            card: "#212021",
            secondary: "#141314",
            foreground: "#eae9ea",
            mutedForeground: "#a8a6a8",
            faint: "#8c8b8c",
            border: "#393739",
            borderSoft: "#282628",
            primary: "#f985e5",
            primaryForeground: "#181718",
            accent: "rgba(249, 133, 229, 0.18)",
            accentForeground: "#f8b7eb",
        },
    },
    {
        id: "teal",
        name: "Teal",
        note: "Cool-neutral paper and a saturated teal. The one that stays legible under fluorescent light and on a washed-out screen.",
        light: {
            background: "#f4f5f5",
            card: "#feffff",
            secondary: "#ebeded",
            foreground: "#202121",
            mutedForeground: "#535454",
            faint: "#6b6d6d",
            border: "#d3d5d5",
            borderSoft: "#e4e5e5",
            primary: "#207c7b",
            primaryForeground: "#ffffff",
            accent: "#c6e7e7",
            accentForeground: "#1d5e5c",
            shadowTint: "36, 39, 39",
        },
        dark: {
            background: "#090b0b",
            card: "#1f2121",
            secondary: "#131414",
            foreground: "#e8eaea",
            mutedForeground: "#a5a7a7",
            faint: "#898c8c",
            border: "#363839",
            borderSoft: "#252727",
            primary: "#3bcecb",
            primaryForeground: "#161718",
            accent: "rgba(59, 206, 203, 0.18)",
            accentForeground: "#54e9e6",
        },
    },
];

export const themePaletteFor = (id: string): ThemePalette | undefined =>
    THEME_PALETTES.find((p) => p.id === id);
